export const RESS = [
  {
    img: "/blog1.png",
    heading: "Pioneering Progress, Shaping tomorrow",
    sub: "Reshape the global industrial landscape with smart plant innovations and lead the AI era.",
    date: "15 Dec, 2024",
    time: "4 min",
    categories: ["Case Studies", "Oil and Gas", "AI"],
    topics: ["Smart Automation"],
    industries: ["Manufacturing"],
    slug: "/Blogs/1",
  },
  {
    img: "/blog2.png",
    heading: "Bridging the Gap: Unified Control Systems for a Smarter Future",
    sub: "Discover how UCS streamline operations, enhancing industrial efficiency and enabling smarter future.",
    date: "05 Dec, 2024",
    time: "2 min",
    categories: ["White Paper", "Chemical", "Predictive Maintence"],
    industries: ["Chemical"],
    topics: ["Predictive Maintence"],
    slug: "/Blogs/2",
    content: {},
  },
  {
    img: "/blog3.png",
    heading: "Nyx, the world's first universal control system",
    date: "05 Dec, 2024",
    time: null,
    categories: ["Product Brochures", "Power", "TPT"],
    file: {
      link: "/pdf.pdf",
      size: "80.9kb",
    },
    slug: "/Blogs/3",
  },
  {
    img: "/blog3.png",
    heading: "Nyx, the world's first universal control system",
    date: "05 Dec, 2024",
    time: null,
    categories: ["Product Brochures", "Power", "TPT"],
    file: {
      link: "/pdf.pdf",
      size: "80.9kb",
    },
    slug: "/Blogs/4",
  },
  {
    img: "/blog3.png",
    heading: "Nyx, the world's first universal control system",
    date: "05 Dec, 2024",
    time: null,
    categories: ["Product Brochures", "Power", "TPT"],
    file: {
      link: "/pdf.pdf",
      size: "80.9kb",
    },
    slug: "/Blogs/5",
  },
  {
    img: "/blog1.png",
    heading: "Pioneering Progress, Shaping tomorrow",
    sub: "Reshape the global industrial landscape with smart plant innovations and lead the AI era.",
    date: "15 Dec, 2024",
    time: "4 min",
    categories: ["Case Studies", "Oil and Gas", "AI"],
    slug: "/Blogs/6",
  },
  {
    img: "/blog2.png",
    heading: "Bridging the Gap: Unified Control Systems for a Smarter Future",
    sub: "Discover how UCS streamline operations, enhancing industrial efficiency and enabling smarter future.",
    date: "05 Dec, 2024",
    time: "2 min",
    categories: ["White Paper", "Chemical", "Predictive Maintence"],
    slug: "/Blogs/7",
  },
  {
    img: "/blog1.png",
    heading: "Pioneering Progress, Shaping tomorrow",
    sub: "Reshape the global industrial landscape with smart plant innovations and lead the AI era.",
    date: "15 Dec, 2024",
    time: "4 min",
    categories: ["Case Studies", "Oil and Gas", "AI"],
    slug: "/Blogs/8",
  },
  {
    img: "/blog2.png",
    heading: "Bridging the Gap: Unified Control Systems for a Smarter Future",
    sub: "Discover how UCS streamline operations, enhancing industrial efficiency and enabling smarter future.",
    date: "05 Dec, 2024",
    time: "2 min",
    categories: ["White Paper", "Chemical", "Predictive Maintence"],
    slug: "/Blogs/9",
  },
  {
    img: "/blog1.png",
    heading: "Pioneering Progress, Shaping tomorrow",
    sub: "Reshape the global industrial landscape with smart plant innovations and lead the AI era.",
    date: "15 Dec, 2024",
    time: "4 min",
    categories: ["Case Studies", "Oil and Gas", "AI"],
    slug: "/Blogs/10",
  },
  {
    img: "/blog2.png",
    heading: "Bridging the Gap: Unified Control Systems for a Smarter Future",
    sub: "Discover how UCS streamline operations, enhancing industrial efficiency and enabling smarter future.",
    date: "05 Dec, 2024",
    time: "2 min",
    categories: ["White Paper", "Chemical", "Predictive Maintence"],
    slug: "/Blogs/11",
  },
  {
    img: "/blog3.png",
    heading: "Nyx, the world's first universal control system",
    date: "05 Dec, 2024",
    time: null,
    categories: ["Product Brochures", "Power", "TPT"],
    file: {
      link: "/pdf.pdf",
      size: "80.9kb",
    },
    slug: "/Blogs/12",
  },
  {
    img: "/blog1.png",
    heading: "Pioneering Progress, Shaping tomorrow",
    sub: "Reshape the global industrial landscape with smart plant innovations and lead the AI era.",
    date: "15 Dec, 2024",
    time: "4 min",
    categories: ["Case Studies", "Oil and Gas", "AI"],
    slug: "/Blogs/10",
  },
  {
    img: "/blog2.png",
    heading: "Bridging the Gap: Unified Control Systems for a Smarter Future",
    sub: "Discover how UCS streamline operations, enhancing industrial efficiency and enabling smarter future.",
    date: "05 Dec, 2024",
    time: "2 min",
    categories: ["White Paper", "Chemical", "Predictive Maintence"],
    slug: "/Blogs/11",
  },
  {
    img: "/blog3.png",
    heading: "Nyx, the world's first universal control system",
    date: "05 Dec, 2024",
    time: null,
    categories: ["Product Brochures", "Power", "TPT"],
    file: {
      link: "/pdf.pdf",
      size: "80.9kb",
    },
    slug: "/Blogs/12",
  },
];
